<?php
/**
 * @var \Algolia\AlgoliaSearch\Block\Algolia $block
 */

$blockInstance= $block->getLayout()->createBlock('Algolia\AlgoliaSearch\Block\Algolia');
$config = $blockInstance->getConfigHelper();
$catalogSearchHelper = $blockInstance->getCatalogSearchHelper();

$placeholder = __('Search for products, categories, ...');

// Render form with autocomplete input
//if ($config->isDefaultSelector()) : ?>
<div id="algoliaAutocomplete" class="block block-search algolia-search-block algolia-search-input"></div>
<?php //endif; ?>
