<?php
/**
 * @var \Algolia\AlgoliaSearch\Block\Algolia $blockInstance
 */
/** @var $configProvider \Magento\Search\ViewModel\ConfigProvider */
$configProvider = $block->getData('configProvider');
$helper = $configProvider->getSearchHelperData();
$allowedSuggestion = $configProvider->isSuggestionsAllowed();
$quickSearchUrl = $allowedSuggestion ? $escaper->escapeUrl($helper->getSuggestUrl()) : '';

$blockInstance= $block->getLayout()->createBlock('Algolia\AlgoliaSearch\Block\Algolia');
$config = $blockInstance->getConfigHelper();
$catalogSearchHelper = $blockInstance->getCatalogSearchHelper();

$placeholder = __('Search for products, categories, ...');

// Render form with autocomplete input
if ($config->isAutoCompleteEnabled()) : ?>
    <div id="algoliaAutocomplete" class="block block-search algolia-search-block algolia-search-input"></div>
<?php else : ?>
<div class="block block-search algolia-search-block">
    <div class="block block-title"><strong><?php echo $block->escapeHtml(__('Search')); ?></strong></div>
    <div class="block block-content">
        <form class="form minisearch" id="search_mini_form"
              action="<?php echo $block->escapeHtml($catalogSearchHelper->getResultUrl()); ?>" method="get">
            <div class="field search" id="algolia-searchbox">
                <label class="label" for="search" data-role="minisearch-label">
                    <span><?= $escaper->escapeHtml(__('Search')) ?></span>
                </label>
                <div class="control">
                    <input id="search"
                           <?php if (!$config->isInstantEnabled()) : ?>
                           data-mage-init='{
                                "quickSearch": {
                                    "formSelector": "#search_mini_form",
                                    "url": "<?= /* @noEscape */ $quickSearchUrl ?>",
                                    "destinationSelector": "#search_autocomplete",
                                    "minSearchLength": "<?= $escaper->escapeHtml($helper->getMinQueryLength()) ?>"
                                }
                           }'
                           <?php endif; ?>
                           type="text"
                           name="<?= $escaper->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                           value="<?= /* @noEscape */ $helper->getEscapedQueryText() ?>"
                           placeholder="<?= $escaper->escapeHtmlAttr($placeholder) ?>"
                           class="input-text algolia-search-input"
                           maxlength="<?= $escaper->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"
                           aria-expanded="false"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?= $block->getChildHtml() ?>
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?= $escaper->escapeHtml(__('Search')) ?>"
                        class="action search"
                        aria-label="Search"
                >
                    <span><?= $escaper->escapeHtml(__('Search')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
<?php endif; ?>
