<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$cartItems = $this->getAllCartItems();
?>
<div id="frequentlyBoughtTogether" class="recommend-component"></div>
<div id="relatedProducts" class="recommend-component"></div>
<div id="trendItems" class="trendsItem recommend-component"></div>
<script>
    window.objectId = <?php echo json_encode($cartItems); ?>;
</script>
