<?php
/** @var \Magento\Catalog\Block\Product\View $block */
$recommendConfig = $this->getAlgoliaRecommendConfiguration();
$product = $block->getProduct();
if (isset($recommendConfig['enabledFBT']) || isset($recommendConfig['enabledRelated']) || isset($recommendConfig['isTrendItemsEnabledInPDP'])):?>
    <div id="frequentlyBoughtTogether" class="recommend-component"></div>
    <div id="relatedProducts" class="recommend-component"></div>
    <div id="trendItems" class="trendsItem recommend-component"></div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Algolia_AlgoliaSearch/recommend" : {
                    "algoliObjectId" : ["<?php echo $product->getId() ?>"]
                }
            }
        }
    </script>
<?php endif;?>
<?php if (isset($recommendConfig['enabledFBT']) || isset($recommendConfig['enabledRelated']) || isset($recommendConfig['isTrendItemsEnabledInPDP'])) { ?>
    <script type="text/x-magento-init">
        {
            "[data-role=tocart-form]": {
                "catalogAddToCart": {}
            }
        }
    </script>
<?php } ?>

