<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$recommendConfig = $this->getAlgoliaRecommendConfiguration();
if (isset($recommendConfig['enabledFBT']) || isset($recommendConfig['enabledRelated'])) {
    $product = $block->getProduct(); ?>
    <div id="frequentlyBoughtTogether" class="recommend-component"></div>
    <div id="relatedProducts" class="recommend-component"></div>
    <script>
        require([
            'jquery',
            'domReady!'
        ], function($){
                window.algoliObjectId = ["<?php echo $product->getId() ?>"];
        });
    </script>
<?php
} ?>
<?php if (isset($recommendConfig['isTrendItemsEnabledInPDP'])) { ?>
    <div id="trendItems" class="trendsItem recommend-component"></div>
<?php } ?>
<?php if (isset($recommendConfig['enabledFBT']) || isset($recommendConfig['enabledRelated']) || isset($recommendConfig['isTrendItemsEnabledInPDP'])) { ?>
    <script type="text/x-magento-init">
        {
            "[data-role=tocart-form]": {
                "catalogAddToCart": {}
            }
        }
    </script>
<?php } ?>
