<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$isEnabled = $block->isTrendingItemEnabled();
if ($isEnabled) {
    $trendConstainer =  'trendItems' . $block->generateUniqueToken(); ?>
    <div id="<?php echo $trendConstainer; ?>" class="trendsItem recommend-component"></div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Algolia_AlgoliaSearch/recommend" : {
                    "recommendTrendContainer" : "<?php echo $trendConstainer; ?>",
                    "numOfTrendsItem" : "<?php echo $block->getData('numOfTrendsItem') ?>",
                    "facetName" : "<?php echo $block->getData('facetName') ?>",
                    "facetValue" : "<?php echo $block->getData('facetValue') ?>"
                }
            }
        }
    </script>
    <script type="text/x-magento-init">
        {
            "[data-role=tocart-form]": {
                "catalogAddToCart": {}
            }
        }
    </script>
<?php
} ?>
