<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$trendConstainer =  "trendItems".$block->generateUniqueToken();
?>
<div id="<?php echo $trendConstainer; ?>" class="trendsItem"></div>
<script>
    window.recommendTrendContainer = "<?php echo $trendConstainer; ?>";
    window.numOfTrendsItem = "<?php echo $block->getData('numOfTrendsItem') ?>";
    window.facetName = "<?php echo $block->getData('facetName') ?>";
    window.facetValue = "<?php echo $block->getData('facetValue') ?>";
</script>
