version: 2

shared: &shared
  working_directory: ~/build_directory/algoliasearch-magento-2
  steps:
    - checkout

    - run:
        name: Override the Algolia extension with the cloned one
        command: |
          cp -R ~/build_directory/algoliasearch-magento-2 ~/magento_directory/vendor/algolia
          cd ~/magento_directory
          sudo composer require algolia/algoliasearch-magento-2
          composer dump-autoload

    - run:
        name: Start database server
        command: |
          sudo service mysql start
          sleep 2
          ps aux | grep mysql

    - run:
        name: Install the extension
        command: |
          cd ~/magento_directory
          sudo service elasticsearch start # for some reasons has to be launched with the step
          sleep 10
          php -dmemory_limit=-1 bin/magento module:disable Magento_WebapiAsync Magento_Amqp Magento_MysqlMq Magento_MessageQueue
          php -dmemory_limit=-1 bin/magento module:enable Algolia_AlgoliaSearch
          sudo chmod -R 777 var/ pub/ generated/
          php -dmemory_limit=-1 bin/magento setup:upgrade
          php -dmemory_limit=-1 bin/magento setup:d:c
          php -dmemory_limit=-1 bin/magento setup:s:d -f

    - run:
        name: Get the right tests config for DB and administration
        command: |
          rm -rf ~/magento_directory/vendor/dotmailer/dotmailer-magento2-extension/Test ~/magento_directory/vendor/dotmailer/dotmailer-magento2-extension-chat/Test
          mv ~/build_directory/algoliasearch-magento-2/dev/tests/install-config-mysql.php ~/magento_directory/dev/tests/integration/etc/install-config-mysql.php

    - run:
        name: Before setup
        command: |
          echo 'memory_limit = 256M' | sudo tee /usr/local/etc/php/php.ini

    - run:
        name: Get keys from dealer
        command: |
          if [ "$CIRCLE_PR_REPONAME" ]; then
            curl -s https://algoliasearch-client-keygen.herokuapp.com | sh >> $BASH_ENV
          fi

    - run:
        name: Run tests
        command: |
          cd ~/magento_directory/dev/tests/integration
          sudo service elasticsearch start # for some reasons has to be launched with the step
          sleep 10

jobs:
  "magento-2.3":
    <<: *shared
    docker:
      - image: algolia/magento2-circleci:2.4.4-php7.4-v1

  "magento-2.4":
    <<: *shared
    docker:
      - image: algolia/magento2-circleci:2.4.4-php7.4-v1

  "quality-tools":
    docker:
      - image: algolia/magento2-circleci:2.4.4-php7.4-v1
    working_directory: ~/build_directory/algoliasearch-magento-2
    steps:
      - checkout
      - run:
          name: Setting permissions
          command: |
            sudo chown circleci:circleci ~/.composer/
      - restore_cache:
          keys:
            - composer-v4-{{ checksum "composer.json" }}
            - composer-v4-

      - run:
          name: Prepare environment
          command: |
            sudo chown circleci:circleci ~/.composer/
            composer global config prefer-stable true
            composer global config minimum-stability dev
            composer global require algolia/magento2-tools

            # We have to do this again because we restore the cache above, overwriting the vendor with the original.
            mkdir ~/magento_directory/vendor/algolia
            # rm -rf algoliasearch-magento-2
            cp -R ~/build_directory/algoliasearch-magento-2 ~/magento_directory/vendor/algolia
            cd ~/magento_directory
            composer dump-autoload
      - save_cache:
          key: composer-v4-{{ checksum "composer.json" }}
          paths:
            - vendor

workflows:
  version: 2
  build:
    jobs:
      - "magento-2.4"
      - "magento-2.3"
      - "quality-tools"
